######################################################################
# Automatically generated by qmake (2.01a) Minggu 7. Agust 07:06:43 2011
######################################################################

TEMPLATE += app
QT += gui declarative
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QmlVs.cpp
