######################################################################
# Automatically generated by qmake (2.01a) Minggu 7. Agust 06:57:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += HelloQt3.cpp
